spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost:5432}/wallet_db
    username: ${PG_USER:postgres_user}
    password: ${PG_PASSWORD:postgres_password}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml


