spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: postgres_user
    password: postgres_password
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
#    default-schema: app_schema
#    parameters:
#      schema: ${spring.liquibase.default-schema}

