version: '3.9'

name: wallet
services:

  app:
    container_name: wallet-app
    image: wallet-app:0.0.1
    restart: on-failure
    depends_on:
      - wallet_db
      - wallet_redis
    ports:
      - "8080:8080"

  psql:
    container_name: wallet_db
    image: postgres:15.4
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: wallet_db
    volumes:
      - database-data:/var/lib/postgresql/data/

  redis:
    container_name: wallet_redis
    image: redis:7.0.12
    restart: on-failure
    ports:
      - "6379:6379"

volumes:
  database-data: